apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-code-with-quarkus-espw
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-cjao-tenant/quarkus/devfile-sample-code-with-quarkus-espw@sha256:6bf90179bcb858c1ce9627f9ef4568e224e44d23785ac30edbac49e8e3aacb96
        name: my-java-quarkus
        resources: {}
status: {}
